baseURL = "https://karaxi404.github.io/"
languageCode = "zh-cn"
title = "我的 Hugo 博客"
theme = "mytheme"
paginate = 10

[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/posts/:slug/"

buildFuture = true
buildDrafts = false
